### ISSUE TITLE
Fix the baseline

### ISSUE THREAD

**Issue by PalumboN** [lucretiomsp/MasterLu#1]
I changed the baseline to:

```ts
baseline: spec

	<baseline>
	spec for: #common do: [
		spec
			package: 'Coypu'
			with: [ spec repository: 'github://lucretiomsp/Coypu' ];
			package: 'Phausto'
			with: [ spec repository: 'github://lucretiomsp/phausto' ];
			package: 'CoypuIDE' with: [ spec repository: 'github://lucretiomsp/CoypuIDE'] .


		"Internal dependencies"
		spec package: 'MasterLu' ]
```

Changes:
- I updated the links to the form `github://<user>/<repo>`
- I removed `spec requires: 'Toplo'` (it must be in `CoypuIDE`)
- I changed the dependency of `pharo-graphics/CoypuIDE` to `lucretiomsp/CoypuIDE` because it needs the [changes in this PR](https://github.com/pharo-graphics/CoypuIDE/pull/32)

---

This _almost_ works: just **Block is missing**, but it is a [dependency of Toplo](https://github.com/pharo-graphics/Toplo/blob/3a851ad00b535c7dc02148d9cf5b72c54029c500/src/BaselineOfToplo/BaselineOfToplo.class.st#L29-L31) that is a [dependency of CoypuIDE](https://github.com/pharo-graphics/CoypuIDE/blob/dd8d0b7b5dccfaf5f09b5768b2c5bc9d9fe1b7dc/BaselineOfCoypuIDE/BaselineOfCoypuIDE.class.st#L12-L15).

But, if you already have Block loaded in the image, it should work.

_Tested in Pharo 12_

**Comment by lucretiomsp** [comment]
I am changing the baseline and check the behaviour on a fresh image
